name: Terraform Apply
on:
  push:
    branches:
      - main

jobs:
  job1:
    name: Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Terraform
        env:
          TERRAFORM_VERSION: '0.12.15'
        run: |
          tf_version=$TERRAFORM_VERSION
          wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
          unzip terraform_"$tf_version"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: docker-compose -f deployment/docker-compose.yml run --rm terraform init

      - name: Terraform validation
        run: terraform validate

      - name: Terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: docker-compose -f deployment/docker-compose.yml run --rm terraform plan

      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: docker-compose -f deployment/docker-compose.yml run --rm terraform destroy -auto-approve